### ISSUE TITLE
`save-identikon` violates its own contract

### ISSUE THREAD

**Issue by greghendershott** [DarrenN/identikon#23]
```racket
#lang racket/base
(require identikon)
(save-identikon "fourty-two"
                'png
                (identikon 1 1 "42"))
```

causes:

```
; save-identikon: broke its own contract
;   promised: boolean?
;   produced: #<void>
;   in: the range of
;       (->*
;        (string? (or/c symbol? string?) image?)
;        (#:quality number?)
;        boolean?)
;   contract from: <pkgs>/identikon/main.rkt
;   blaming: <pkgs>/identikon/main.rkt
;    (assuming the contract is correct)
;   at: <pkgs>/identikon/main.rkt:23.24
```

From what I can tell from a quick look at the source, this is because `save-identikon` calls functions that return `void`. Or, it raises an error.

1. One fix would be to have `save-identikon` return `#t`.
2. Another fix would be to change the contract (in `main.rkt` and the Scrbibble doc) to say it returns `void?`.

I think 2 better and almost went ahead and submitted a PR with that. But thought I should ask first.

**Comment by DarrenN** [comment]
Ah yup I see the problem. Also realized there's no test for `save-identikon` which is why this wasn't caught. Will address both problems.

**Comment by DarrenN** [comment]
@greghendershott went ahead and updated the contract to specify `(or/c void? exn:fail?)` and updated the docs. It's been merged, not sure how long before Racket's package system picks up the new version.

**Comment by DarrenN** [comment]
@greghendershott I kicked off a package rescan, so:

> The results will be available after the next index refresh, which is scheduled for Saturday, May 25th, 2019 7:44:25pm (UTC)

**Comment by greghendershott** [comment]
Thanks!
