### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by greghendershott** [DarrenN/identikon#6]
Very cool!

A few comments/issues; apologies for lumping them into one GitHub issue.

1. README: [`racket-mode`](https://github.com/greghendershott/racket-mode) also displays images in the REPL. I'd be grateful if you could mention it, too.

2. README: A third dependency people need to `raco pkg install` is `quickcheck`.

    quickcheck seems to have a mistake -- it `provide`s but doesn't define `check-result?`. After I commented out that, it built fine. I [reported that to quickcheck](https://github.com/ifigueroap/racket-quickcheck/issues/6).

3. Your `load-plug-in` assumes the current directory. So when I made this little test program in my /tmp folder:

```
#lang racket
(require identikon/identikon)
(identikon 300 300 "racket")
```

I got:

```
; default-load-handler: cannot open module file
;   module path: #<path:/tmp/rules/default.rkt>
;   path: /tmp/rules/default.rkt
;   system error: No such file or directory; errno=2
; Context:
;  /tmp/id.rkt:1:1 [running body]
;  /Users/greg/src/racket/identikon/identikon.rkt:63:0 core16
```

I worked around it by setting the curdir to your collection:

```
#lang racket
(require identikon/identikon)
(parameterize ([current-directory "/Users/greg/src/racket/identikon"])
  (identikon 300 300 "racket"))
```

Then it displays an awesome identikon!

But this probably isn't the way it should work. Maybe you need `define-runtime-path` to reach files relative to your own source files. Let me know if you have any questions, or if you'd like me to try to submit a pull request.

Again, very cool!

**Comment by greghendershott** [comment]
I opened an issue for quickcheck: https://github.com/ifigueroap/racket-quickcheck/issues/6

**Comment by greghendershott** [comment]
I submitted [a pull request](https://github.com/DarrenN/identikon/pull/7) for the 3rd issue.

**Comment by DarrenN** [comment]
Thanks @greghendershott - good catch on `racket-mode`, I use it in Emacs (and it works great btw) but spaced when writing the blog post. Will get that updated.

![img](https://dl.dropbox.com/s/sb0f5av6fzvtcqv/Screenshot%202014-11-28%2018.14.30.png?dl=0)

Will also update the information for quickcheck. This is really a question for @ifigueroap but I wasn't able to use both `rackunit` and `quickcheck` in the `tests` submodule as it looks like quickcheck overwrites `check`. Do you have any experience working with both of them together?

**Comment by greghendershott** [comment]
> This is really a question for @ifigueroap but I wasn't able to use both rackunit and quickcheck in the tests submodule as it looks like quickcheck overwrites check. Do you have any experience working with both of them together?

The usual way of handling name conflicts like that is that `require` has some optional sub-forms like `only-in`, `prefix-in` and `rename-in`.

So you could do something like `(require rackunit (prefix-in q: quickcheck))`: `check` would be from rackunit and `q:check` would be from `quickcheck`. Or you could `prefix-in` both. As you prefer.

I haven't used `quickcheck` much, and never alongside `rackunit`, so I don't know for sure if it's that simple, but usually it is.  If you do ping @ifgueroap maybe you could suggest they add that as a tip to their README.

**Comment by greghendershott** [comment]
Thanks for updating the README to add quickcheck and racket-mode!

One nit: That screenshot is of Geiser (I'm pretty sure from the `racket@>` style prompt).

I'm definitely not objecting to that. (And BTW I wasn't asking you to remove Geiser from the README, just to add racket-mode).

But I do want to make sure you realize you're using Geiser not racket-mode. Especially if you give me a bug report about it someday. :P

**Comment by DarrenN** [comment]
Ahh funny okay, I have `racket-mode` installed, but didn't realize I was getting the REPL through Geiser.

**Comment by DarrenN** [comment]
Allrighty, I just needed to configure `racket-mode` to point to where I keep Racket, and I got the REPL working:

![racket-mode](https://dl.dropbox.com/s/959udfzh8ysoc85/Screenshot%202015-01-10%2011.44.31.png?dl=0)

Very cool. Thanks for your help on this!

**Comment by ifigueroap** [comment]
Maybe this is a bit late, but now it is possible to use both RackUnit and quickcheck. First, there is no conflict regarding the `check` symbol. Now quickcheck exports `quickcheck` and `quickcheck/config` symbols. Furthermore, the new `rackunit/quickcheck` collection defines some forms, `check-property` and `check-property/config`, where failed properties raise proper RackUnit exceptions. It is also possible to add property-instance-specific metadata to the eventual exceptions using the `add-property-check-info` form, designed in the same spirit as `with-check-info`.

**Comment by DarrenN** [comment]
very cool, thanks for the heads up @ifigueroap
